// Map and etc.
export const CHANGE_DISTANCE = 'CHANGE_DISTANCE';
export const CHANGE_ROUTE_ITEMS = 'CHANGE_ROUTE_ITEMS';

export const REQUEST_SAVE_ROUTE = 'REQUEST_SAVE_ROUTE';
export const REQUEST_SAVE_ROUTE_SUCCESS = 'REQUEST_SAVE_ROUTE_SUCCESS';
export const REQUEST_SAVE_ROUTE_ERROR = 'REQUEST_SAVE_ROUTE_ERROR';